Backend posting feed
software-students-fall2021/project-setup-potluck pull request #119
Opened 2021-11-23 16:38 UTC by Wajahat-Mirza

Workflow: 

1. After uploading the post, there is a route "postFeedRoute.js" that handles POST calls
2. postFeedRoute calls onto the model "postModel.js" where Schema has 5 attributes/keys
3. In app.js, there is function storage on multer to store uploaded files, app.get("/postfeed") func, and app.post("/postfeed") func.

2021-11-23 16:54 UTC, HaveACookie requested changes
Using readfileSync will block the server during certain operations and shouldn't be used, consider using multer/readfile (readfile is readfileSync's asynchronous equivalent) or multer+base64 to encode an image into a form that can be stored into mongodb.

2021-11-23 16:57 UTC, Wajahat-Mirza commented
I looked into details on storing images in mongodb. It is advisable not to store them on a server with a reference rather than calling/storing them to mongodb directly (e.g use of S3 with AWS) 
I will look up on readfile

2021-12-01 02:58 UTC, Wajahat-Mirza commented
Thank you @HaveACookie @seungguini for the help :)

2021-12-01 05:18 UTC, HaveACookie approved these changes

2021-12-01 05:23 UTC, merged